# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ab7a1cbbcd861bf793aedcba914df78ca7a51f0ba90a68793dbb5520e416e76b16572d4a3daf83909385b3de4402a5e3944a5b1531ddd64775e1a10cbccdaca

test:
  secret_key_base: c8c52ec8b1f90467225e6f741ca1f64afc537894d3d718b71b953962b9034673dbc0b53610cfc3179ec482316e2b578c3f089344daae2b65630f6c6834deee39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
